<?php
/**
 * Template Name: Portal Live
 * Description: A custom template for displaying the live streaming page.
 *
 * @package Avantage_Baccarat
 */
get_header();

// Load styles before content to prevent FOUC
get_template_part( 'template-parts/portal-styles' );
?>

    <main id="primary" class="site-main">
        
        <?php get_template_part( 'template-parts/portal-header' ); ?>
        
        <div class="container py-2 live-page-wrap" id="portal-content">

            <!-- Live Content -->
            <div class="live-page-content">
                

                <div class="live-header">
                    <img src="<?php echo get_template_directory_uri(); ?>/images/live.png" alt="Live Appearance" class="live-icon">
                    <h1 class="live-title">LIVE APPEARANCE</h1>
                </div>

                <section class="live-intro-text">
                    <p>There are two types of appearances: Kick Network and on the World Broadcast Network.</p>
                    <p>We believe live competition creates real connection and lasting influence.</p>
                    <p>Influencers will automatically be eligible to appear in all 52 world tour weekend events and the year-long $100 million World Championship competition.</p>
                </section>

                    <div class="live-separator"></div>
                    <h2 class="live-section-heading">REQUEST A LIVE APPEARANCE ON THE WORLD NETWORK</h2>
                    <div class="live-separator"></div>

                    <div class="live-intro-item live-intro-item-wide">
                        <!-- <img src="http://localhost:3845/assets/e219a018d57aa99645c7614899877f794585b3a7.png" alt="Bullet"> -->
                        <p>Influencers are automatically enabled to stream on Kick—no application required. Simply keep us informed of your scheduled broadcasts so we can publish and promote them. You’ll earn a 1% equity bonus on all play generated by all viewers on both Kick and the Avantage Broadcast Network.</p>
                    </div>

                    <div class="live-form-block">
                        <form id="live-request-form">
                            <p class="live-label">Request Day &amp; Start Time (1 hour)</p>
                            <div class="live-input-row live-input-row-2">
                                <div class="live-field">
                                    <label class="live-field-label" for="la_day">Day</label>
                                    <input type="date" name="la_day" id="la_day" class="live-input">
                                </div>
                                <div class="live-field">
                                    <label class="live-field-label" for="la_backup_day">Backup Day</label>
                                    <input type="date" name="la_backup_day" id="la_backup_day" class="live-input">
                                </div>
                            </div>
                            <div class="live-input-row live-input-row-2">
                                <div class="live-field">
                                    <label class="live-field-label" for="la_start_time">Start Time</label>
                                    <input type="time" name="la_start_time" id="la_start_time" class="live-input">
                                </div>
                                <div class="live-field">
                                    <label class="live-field-label" for="la_backup_start_time">Backup Start Time</label>
                                    <input type="time" name="la_backup_start_time" id="la_backup_start_time" class="live-input">
                                </div>
                            </div>
                            <div class="live-input-row">
                                <div class="live-field live-field--full">
                                    <label class="live-field-label" for="la_opponent_handle">Confirmed Opponent Handle</label>
                                    <input type="text" name="la_opponent_handle" id="la_opponent_handle" class="live-input live-input-lg" placeholder="@handle...">
                                </div>
                            </div>
                            <div class="live-input-row">
                                <div class="live-field live-field--full">
                                    <label class="live-field-label" for="la_backup_opponent_handle">Confirmed Backup Opponent Handle</label>
                                    <input type="text" name="la_backup_opponent_handle" id="la_backup_opponent_handle" class="live-input live-input-lg" placeholder="@handle...">
                                </div>
                            </div>
                            <div class="live-input-row">
                                <div class="live-field live-field--full">
                                    <label class="live-field-label" for="la_url">Unique Live Appearance URL to Share</label>
                                    <input type="url" name="la_url" id="la_url" class="live-input live-input-lg" placeholder="https://...">
                                </div>
                            </div>
                            <div class="live-submit-row">
                                <button type="submit" class="live-submit" id="live-request-btn">REQUEST</button>
                            </div>
                            <div id="live-request-msg" class="live-request-msg" style="display:none;"></div>
                        </form>

                        <p class="live-label">Status of Request</p>
                        <div class="live-status" id="live-request-status">—</div>

                        <div id="live-url-wrap" style="display:none;">
                            <p class="live-label">Your Live Appearance URL</p>
                            <div class="live-url" id="live-url-display"></div>
                        </div>
                    </div>

                    <div class="live-separator"></div>
                    <h2 class="live-section-heading">KICK BROADCASTING SCHEDULE</h2>

                    <p class="live-copy">Current Schedule</p>

                    <div id="kick-schedule-list">
                        <?php
                        $ks_schedule = get_user_meta( get_current_user_id(), '_kick_broadcasting_schedule', true );
                        if ( is_array( $ks_schedule ) && ! empty( $ks_schedule ) ) :
                            foreach ( $ks_schedule as $ks_i => $ks_item ) :
                                $ks_day_fmt   = ! empty( $ks_item['day'] )        ? date_i18n( 'D, M j', strtotime( $ks_item['day'] ) )        : '';
                                $ks_start_fmt = ! empty( $ks_item['start_time'] ) ? date_i18n( 'g:i A',   strtotime( $ks_item['start_time'] ) ) : '';
                                $ks_end_fmt   = ! empty( $ks_item['end_time'] )   ? date_i18n( 'g:i A',   strtotime( $ks_item['end_time'] ) )   : '';
                                $ks_label     = trim( $ks_day_fmt . ( $ks_start_fmt ? ', ' . $ks_start_fmt : '' ) . ( $ks_end_fmt ? ' - ' . $ks_end_fmt : '' ) );
                        ?>
                        <div class="live-schedule-item" data-index="<?php echo esc_attr( $ks_i ); ?>">
                            <span><?php echo esc_html( $ks_label ); ?></span>
                            <button type="button" class="live-inline-btn kick-cancel-btn" data-index="<?php echo esc_attr( $ks_i ); ?>">cancel</button>
                        </div>
                        <?php endforeach; else : ?>
                        <p class="live-copy-muted">No schedule entries yet.</p>
                        <?php endif; ?>
                    </div>

                    <p class="live-copy">Post Additional Schedule</p>
                    <form id="kick-schedule-form">
                        <div class="live-input-row">
                            <div class="live-field live-field--full">
                                <label class="live-field-label" for="ks_day">Date</label>
                                <input type="date" name="ks_day" id="ks_day" class="live-input live-input-md">
                            </div>
                        </div>
                        <div class="live-input-row live-input-row-2">
                            <div class="live-field">
                                <label class="live-field-label" for="ks_start_time">Start Time</label>
                                <input type="time" name="ks_start_time" id="ks_start_time" class="live-input live-input-md">
                            </div>
                            <div class="live-field">
                                <label class="live-field-label" for="ks_end_time">End Time</label>
                                <input type="time" name="ks_end_time" id="ks_end_time" class="live-input live-input-md">
                            </div>
                        </div>
                        <div class="live-submit-row">
                            <button type="submit" class="live-submit" id="kick-schedule-btn">SUBMIT</button>
                        </div>
                        <div id="kick-schedule-msg" class="live-request-msg" style="display:none;"></div>
                    </form>

                    <div class="live-separator live-separator-white"></div>

                    <h2 class="live-section-heading live-section-heading--how">HOW TO STREAM ON KICK</h2>

                    <div class="accordion-gradient-container">
                        <div class="accordion custom-accordion" id="liveStreamAccordion">

                            <!-- Set Up Your Stream -->
                            <div class="accordion-item mb-3">
                                <h2 class="accordion-header" id="headingSetup">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSetup" aria-expanded="true" aria-controls="collapseSetup">
                                        <span class="question-text">Set Up Your Stream</span>
                                    </button>
                                </h2>
                                <div id="collapseSetup" class="accordion-collapse collapse show" aria-labelledby="headingSetup" data-bs-parent="#liveStreamAccordion">
                                    <div class="accordion-body">
                                        <p><strong>Purpose</strong></p>
                                        <p>By the time you leave this tab you will have:</p>
                                        <ul>
                                            <li>Created your Kick channel.</li>
                                            <li>Connected OBS Studio so your stream can go live.</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <!-- Warm-Up Mindset -->
                            <div class="accordion-item mb-3">
                                <h2 class="accordion-header" id="headingWarmup">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWarmup" aria-expanded="false" aria-controls="collapseWarmup">
                                        <span class="question-text">Warm-Up Mindset</span>
                                    </button>
                                </h2>
                                <div id="collapseWarmup" class="accordion-collapse collapse" aria-labelledby="headingWarmup" data-bs-parent="#liveStreamAccordion">
                                    <div class="accordion-body">
                                        <p>Every athlete warms up before a game.</p>
                                        <p>Every performer rehearses before stepping on stage.</p>
                                        <p>Streaming is no different.</p>
                                        <p>Before you go live:</p>
                                        <ul>
                                            <li>Play two or three contests privately to get comfortable.</li>
                                            <li>Get your voice in rhythm.</li>
                                            <li>Review the Roads so you're already in tune with the game's flow.</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <!-- Why Kick? -->
                            <div class="accordion-item mb-3">
                                <h2 class="accordion-header" id="headingWhyKick">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWhyKick" aria-expanded="false" aria-controls="collapseWhyKick">
                                        <span class="question-text">Why Kick?</span>
                                    </button>
                                </h2>
                                <div id="collapseWhyKick" class="accordion-collapse collapse" aria-labelledby="headingWhyKick" data-bs-parent="#liveStreamAccordion">
                                    <div class="accordion-body">
                                        <p>Kick is the fastest-growing channel for streaming online gaming platform for live gaming and commentary — and it's where Avantage streams begin.</p>
                                        <p><strong>Important:</strong> On Kick, your account is your channel. When you sign up, you automatically create both.</p>
                                    </div>
                                </div>
                            </div>

                            <!-- Step 1 – Create Your Kick Channel -->
                            <div class="accordion-item mb-3">
                                <h2 class="accordion-header" id="headingStep1">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseStep1" aria-expanded="false" aria-controls="collapseStep1">
                                        <span class="question-text">Step 1 – Create Your Kick Channel</span>
                                    </button>
                                </h2>
                                <div id="collapseStep1" class="accordion-collapse collapse" aria-labelledby="headingStep1" data-bs-parent="#liveStreamAccordion">
                                    <div class="accordion-body">
                                        <p><strong>1. Go to Kick.com → Sign Up.</strong></p>
                                        <ul>
                                            <li>Use email, Google, or Apple.</li>
                                            <li>Choose a username – this becomes your channel name.</li>
                                            <li>Confirm your email (Kick sends a link).</li>
                                        </ul>
                                        <p><strong>2. After confirming, Sign In.</strong></p>
                                        <ul>
                                            <li>Click your profile picture (top right) → Creator Dashboard.</li>
                                            <li>Upload a profile photo (headshot or "stage" shot).</li>
                                            <li>Upload a banner (simple background with your name or Avantage Baccarat).</li>
                                            <li>Free design tools: Canva.com or Fotor.com.</li>
                                            <li>Write a short description (2–3 lines):
                                                <ul>
                                                    <li>"Live Avantage Baccarat commentary — join me as I call the action in real time."</li>
                                                    <li>"Official Avantage Baccarat streamer. Watch, follow trends, and feel the energy with me."</li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <!-- Step 2 – Connect OBS Studio -->
                            <div class="accordion-item mb-3">
                                <h2 class="accordion-header" id="headingStep2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseStep2" aria-expanded="false" aria-controls="collapseStep2">
                                        <span class="question-text">Step 2 – Connect OBS Studio</span>
                                    </button>
                                </h2>
                                <div id="collapseStep2" class="accordion-collapse collapse" aria-labelledby="headingStep2" data-bs-parent="#liveStreamAccordion">
                                    <div class="accordion-body">
                                        <p><strong>What is OBS?</strong></p>
                                        <p>Open Broadcaster Software (OBS) is the free program that acts as the control room for your stream.</p>
                                        <ul>
                                            <li>It brings together your camera, microphone, and game screen.</li>
                                            <li>It lets you arrange how everything looks.</li>
                                            <li>It sends that feed to your Kick channel so your stream actually goes live.</li>
                                        </ul>
                                        <p><strong>How to Set It Up</strong></p>
                                        <ol>
                                            <li>In your Kick Creator Dashboard → Settings → Stream → copy your Stream URL and Stream Key.</li>
                                            <li>Download OBS Studio from <a href="https://obsproject.com/" style="color: #b8972f;">obsproject.com</a>.</li>
                                            <li>Open OBS → Settings → Stream → select Custom Service → paste in the URL and Key.</li>
                                            <li>Select a suitable category such as Games or Entertainment.</li>
                                            <li>In OBS, click Start Streaming.</li>
                                            <li>You're live on your Kick channel.</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>

                            <!-- Reassurance -->
                            <div class="accordion-item mb-3">
                                <h2 class="accordion-header" id="headingReassurance">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseReassurance" aria-expanded="false" aria-controls="collapseReassurance">
                                        <span class="question-text">Reassurance</span>
                                    </button>
                                </h2>
                                <div id="collapseReassurance" class="accordion-collapse collapse" aria-labelledby="headingReassurance" data-bs-parent="#liveStreamAccordion">
                                    <div class="accordion-body">
                                        <p>You now have your channel, your gear, and your settings.</p>
                                        <p>Take a deep breath, speak with confidence, and enjoy your first broadcast.</p>
                                        <p>Every stream will get easier — and every voice you reach builds your community.</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            
            </div>
        
        <!-- Fixed Footer Links -->
        <div class="footer-links-fixed">
            <a href="#" class="footer-link">Terms</a>
            <span class="footer-separator">|</span>
            <a href="#" class="footer-link">Privacy</a>
        </div>
    </main><!-- #main -->

<?php
$_live_nonce     = wp_create_nonce( 'request_live_appearance_nonce' );
$_schedule_nonce = wp_create_nonce( 'kick_schedule_nonce' );
?>
<script>
(function () {
    var _liveAjaxUrl    = <?php echo wp_json_encode( admin_url( 'admin-ajax.php' ) ); ?>;
    var _liveNonce      = <?php echo wp_json_encode( $_live_nonce ); ?>;
    var _scheduleNonce  = <?php echo wp_json_encode( $_schedule_nonce ); ?>;

    function setStatus(label, statusKey) {
        var el = document.getElementById('live-request-status');
        if (!el) return;
        el.textContent = label;
        el.className   = 'live-status' + (statusKey === 'confirmed' ? ' live-status--confirmed' : ' live-status--pending');
    }

    function setUrl(url) {
        var wrap = document.getElementById('live-url-wrap');
        var el   = document.getElementById('live-url-display');
        if (!wrap || !el) return;
        if (url) {
            el.textContent      = url;
            wrap.style.display  = '';
        } else {
            wrap.style.display  = 'none';
        }
    }

    function showMsg(text, isError) {
        var el = document.getElementById('live-request-msg');
        if (!el) return;
        el.textContent   = text;
        el.className     = 'live-request-msg live-request-msg--' + (isError ? 'error' : 'success');
        el.style.display = '';
    }

    // Load the latest status on page load
    (function loadStatus() {
        var fd = new FormData();
        fd.append('action', 'get_live_appearance_status');
        fd.append('nonce',  _liveNonce);
        fetch(_liveAjaxUrl, { method: 'POST', body: fd })
            .then(function(r) { return r.json(); })
            .then(function(res) {
                if (res.success && res.data.found) {
                    setStatus(res.data.status_label, res.data.status_key);
                    setUrl(res.data.url);
                }
            }).catch(function() {});
    })();

    // Form submission
    var form = document.getElementById('live-request-form');
    if (form) {
        form.addEventListener('submit', function (e) {
            e.preventDefault();
            var btn = document.getElementById('live-request-btn');
            if (btn) { btn.disabled = true; btn.textContent = 'SUBMITTING...'; }
            var fd = new FormData(form);
            fd.append('action', 'request_live_appearance');
            fd.append('nonce',  _liveNonce);
            fetch(_liveAjaxUrl, { method: 'POST', body: fd })
                .then(function(r) { return r.json(); })
                .then(function(res) {
                    if (btn) { btn.disabled = false; btn.textContent = 'REQUEST'; }
                    if (res.success) {
                        showMsg(res.data.message || 'Request submitted successfully.', false);
                        setStatus(res.data.status_label, res.data.status_key);
                        setUrl(res.data.url);
                        form.reset();
                    } else {
                        var msg = (res.data && res.data.message) ? res.data.message : 'An error occurred.';
                        showMsg(msg, true);
                    }
                }).catch(function () {
                    if (btn) { btn.disabled = false; btn.textContent = 'REQUEST'; }
                    showMsg('Network error. Please try again.', true);
                });
        });
    }

    // ── Kick Broadcasting Schedule ────────────────────────────

    function fmtTime(t) {
        if (!t) return '';
        var parts = t.split(':');
        var h = parseInt(parts[0], 10);
        var m = parts[1];
        var ampm = h >= 12 ? 'PM' : 'AM';
        h = h % 12 || 12;
        return h + (m && m !== '00' ? ':' + m : '') + ' ' + ampm;
    }

    function fmtDay(d) {
        if (!d) return '';
        var p = d.split('-');
        var dt = new Date(parseInt(p[0], 10), parseInt(p[1], 10) - 1, parseInt(p[2], 10));
        return dt.toLocaleDateString('en-US', {weekday: 'short', month: 'short', day: 'numeric'});
    }

    function renderSchedule(schedule) {
        var list = document.getElementById('kick-schedule-list');
        if (!list) return;
        list.innerHTML = '';
        if (!schedule || schedule.length === 0) {
            list.innerHTML = '<p class="live-copy-muted">No schedule entries yet.</p>';
            return;
        }
        schedule.forEach(function(item, i) {
            var label = fmtDay(item.day);
            if (item.start_time) label += ', ' + fmtTime(item.start_time);
            if (item.end_time)   label += ' - ' + fmtTime(item.end_time);
            var div = document.createElement('div');
            div.className = 'live-schedule-item';
            div.setAttribute('data-index', i);
            div.innerHTML = '<span>' + label + '</span>' +
                '<button type="button" class="live-inline-btn kick-cancel-btn" data-index="' + i + '">cancel</button>';
            list.appendChild(div);
        });
    }

    function showScheduleMsg(text, isError) {
        var el = document.getElementById('kick-schedule-msg');
        if (!el) return;
        el.textContent   = text;
        el.className     = 'live-request-msg live-request-msg--' + (isError ? 'error' : 'success');
        el.style.display = '';
        setTimeout(function() { el.style.display = 'none'; }, 4000);
    }

    var ksForm = document.getElementById('kick-schedule-form');
    if (ksForm) {
        ksForm.addEventListener('submit', function(e) {
            e.preventDefault();
            var btn = document.getElementById('kick-schedule-btn');
            if (btn) { btn.disabled = true; btn.textContent = 'SAVING...'; }
            var fd = new FormData(ksForm);
            fd.append('action', 'add_kick_schedule');
            fd.append('nonce', _scheduleNonce);
            fetch(_liveAjaxUrl, {method: 'POST', body: fd})
                .then(function(r) { return r.json(); })
                .then(function(res) {
                    if (btn) { btn.disabled = false; btn.textContent = 'SUBMIT'; }
                    if (res.success) {
                        renderSchedule(res.data.schedule);
                        ksForm.reset();
                        showScheduleMsg('Schedule added.', false);
                    } else {
                        showScheduleMsg((res.data && res.data.message) ? res.data.message : 'Error saving.', true);
                    }
                }).catch(function() {
                    if (btn) { btn.disabled = false; btn.textContent = 'SUBMIT'; }
                    showScheduleMsg('Network error. Please try again.', true);
                });
        });
    }

    var ksList = document.getElementById('kick-schedule-list');
    if (ksList) {
        ksList.addEventListener('click', function(e) {
            var cancelBtn = e.target.closest('.kick-cancel-btn');
            if (!cancelBtn) return;
            var idx = parseInt(cancelBtn.getAttribute('data-index'), 10);
            cancelBtn.disabled = true;
            var fd = new FormData();
            fd.append('action', 'delete_kick_schedule');
            fd.append('nonce', _scheduleNonce);
            fd.append('index', idx);
            fetch(_liveAjaxUrl, {method: 'POST', body: fd})
                .then(function(r) { return r.json(); })
                .then(function(res) {
                    if (res.success) {
                        renderSchedule(res.data.schedule);
                    } else {
                        cancelBtn.disabled = false;
                        showScheduleMsg((res.data && res.data.message) ? res.data.message : 'Error deleting.', true);
                    }
                }).catch(function() {
                    cancelBtn.disabled = false;
                    showScheduleMsg('Network error. Please try again.', true);
                });
        });
    }
})();
</script>
<?php
get_template_part( 'template-parts/portal-scripts' );
get_footer();
